# Generated by Django 3.2.7 on 2021-09-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_in_order',
            new_name='ProductInOrder',
        ),
    ]
